### ISSUE TITLE
[Bugs] AMF shall include context RAND in UEAuthenticateRequest when Synch Failure

### ISSUE THREAD

**Issue by kishiguro** [free5gc/free5gc#176] opened 2021-02-15 20:43 UTC
## Describe the bug
AMF fails to recover from Sync Failure scenario described in TS 24.501 5.4.1.3.7 case f.  AMF shall include context RAND in UEAuthenticateRequest message when it receives AuthenticationFailure message from UE with cause of SynchFailure.

## To Reproduce
UE to send AuthenticationFailure with cause of SynchFailure.

## Expected behavior
AMF include context RAND in UEAuthenticateRequest message and recover from Sync Failure scenario.

## Environment (please complete the following information):
 - free5GC Version: 3.0.5
 - OS: Ubuntu 18.04
 - Kernel version: 5.0.0-23-generic
- go version: 1.15.8 linux/amd64

## Pull Request
[Pull Request](https://github.com/free5gc/amf/pull/27) for the fix.

**Comment by free5gc-org** [comment] 2021-02-19 16:47
@kishiguro 

I didn't find any RAND related description in TS 24.501 5.4.1.3.7 case f:

```
f) Authentication failure (5GMM cause #21 "synch failure").
The UE shall send an AUTHENTICATION FAILURE message, with 5GMM cause #21 "synch failure", to the
network and start the timer T3520 (see example in figure 5.4.1.3.7.1). Furthermore, the UE shall stop any of the
retransmission timers that are running (e.g. T3510, T3517 or T3521). Upon the first receipt of an
AUTHENTICATION FAILURE message from the UE with the 5GMM cause #21 "synch failure", the network
shall use the returned AUTS parameter from the authentication failure parameter IE in the AUTHENTICATION
FAILURE message, to re-synchronise. The re-synchronisation procedure requires the AMF to delete all unused
authentication vectors for that SUPI and obtain new vectors from the UDM/AUSF. When re-synchronisation is
complete, the network shall initiate the 5G AKA based primary authentication and key agreement procedure.
Upon receipt of the AUTHENTICATION REQUEST message, the UE shall stop the timer T3520, if running.
NOTE 4: Upon receipt of two consecutive AUTHENTICATION FAILURE messages from the UE with 5GMM
cause #21 "synch failure", the network may terminate the 5G AKA based primary authentication and key
agreement procedure by sending an AUTHENTICATION REJECT message.
If the network is validated successfully (a new AUTHENTICATION REQUEST message is received which
contains a valid SQN and MAC) while T3520 is running, the UE shall send the AUTHENTICATION
RESPONSE message to the network and shall start any retransmission timers (e.g. T3510, T3517 or T3521), if
they were running and stopped when the UE received the first failed AUTHENTICATION REQUEST message.
Upon receipt of an AUTHENTICATION REJECT message, the UE shall perform the actions as specified in
subclause 5.4.1.3.5.
```

**Comment by free5gc-org** [comment] 2021-03-11 17:05
> @kishiguro
> 
> I didn't find any RAND related description in TS 24.501 5.4.1.3.7 case f:
> 
> ```
> f) Authentication failure (5GMM cause #21 "synch failure").
> The UE shall send an AUTHENTICATION FAILURE message, with 5GMM cause #21 "synch failure", to the
> network and start the timer T3520 (see example in figure 5.4.1.3.7.1). Furthermore, the UE shall stop any of the
> retransmission timers that are running (e.g. T3510, T3517 or T3521). Upon the first receipt of an
> AUTHENTICATION FAILURE message from the UE with the 5GMM cause #21 "synch failure", the network
> shall use the returned AUTS parameter from the authentication failure parameter IE in the AUTHENTICATION
> FAILURE message, to re-synchronise. The re-synchronisation procedure requires the AMF to delete all unused
> authentication vectors for that SUPI and obtain new vectors from the UDM/AUSF. When re-synchronisation is
> complete, the network shall initiate the 5G AKA based primary authentication and key agreement procedure.
> Upon receipt of the AUTHENTICATION REQUEST message, the UE shall stop the timer T3520, if running.
> NOTE 4: Upon receipt of two consecutive AUTHENTICATION FAILURE messages from the UE with 5GMM
> cause #21 "synch failure", the network may terminate the 5G AKA based primary authentication and key
> agreement procedure by sending an AUTHENTICATION REJECT message.
> If the network is validated successfully (a new AUTHENTICATION REQUEST message is received which
> contains a valid SQN and MAC) while T3520 is running, the UE shall send the AUTHENTICATION
> RESPONSE message to the network and shall start any retransmission timers (e.g. T3510, T3517 or T3521), if
> they were running and stopped when the UE received the first failed AUTHENTICATION REQUEST message.
> Upon receipt of an AUTHENTICATION REJECT message, the UE shall perform the actions as specified in
> subclause 5.4.1.3.5.
> ```

@kishiguro 
Where did you find the RAND related description? I can't find it in TS 24.501 5.4.1.3.7 case f.

**Comment by kishiguro** [comment] 2021-03-15 06:49
you are right, we still investigating the root cause of the error we encountered.  please let us take a few more days.

**Comment by free5gc-org** [comment] 2021-04-27 17:20
> you are right, we still investigating the root cause of the error we encountered. please let us take a few more days.

@kishiguro 
Did you find the root cause?

**Comment by free5gc-org** [comment] 2021-07-11 08:48
@kishiguro 
Any update?

**Comment by free5gc-org** [comment] 2021-07-12 14:05
@kishiguro 
Do you have successful pcap for reference?

**Comment by jay16213** [comment] 2021-07-22 12:45
@free5gc-org, I think this bugfix PR is no problem.
When AMF receive a NAS message "Authentication Failure" with 5GMM cause "synch failure" from UE, AMF should send a UEAuthentication Request to AUSF, with ResynchronizationInfo filled (the related SBI procedure and request/response type is defined TS 29.509 5.2 and 6.1.6.2.2).
![image](https://user-images.githubusercontent.com/17217471/126639999-c09e71bd-11c4-4ee3-a8fc-c87e441093cb.png)

The structure of ResynchronizationInfo is defined in TS 29.503 6.3.6.2.6
![image](https://user-images.githubusercontent.com/17217471/126639911-f4ff82b8-287f-4a26-95c4-559b0be685f2.png)

You can see that RAND is a mandatory field, which is missed by current version of AMF.

**Comment by free5gc-org** [comment] 2021-07-23 11:49
@jay16213 

Thanks for your clarification!
The PR is merged.

**Closed** 2021-07-23 11:49 UTC
Labels: AMF, bug, with PR

**Comment by anvi55** [comment] 2021-07-26 12:21
I added the fix from the above mentioned PR to my local setup. still it fails. Any suggestions to recover from sync failure,
I replaced new SIM card for time being to make UE attach. But if i replace again the sync failure sim card even after 3-4 days sync failure exists. Rebooted the UE multiple times still it fails

below is the changes which i added. please let me know any other changes to be made for sync failure issue

root@ddamf:~/anu/5gsim/pw5gc# git diff NFs/amf/gmm/handler.go
diff --git a/pw5gc/NFs/amf/gmm/handler.go b/pw5gc/NFs/amf/gmm/handler.go
index 737f269..7aca39f 100644
--- a/pw5gc/NFs/amf/gmm/handler.go
+++ b/pw5gc/NFs/amf/gmm/handler.go
@@ -465,11 +465,18 @@ func HandleRegistrationRequest(ue *context.AmfUe, anType models.AccessType, proc
                ue.NgKsi.Tsc = models.ScType_MAPPED
        }
        ue.NgKsi.Ksi = int32(registrationRequest.NgksiAndRegistrationType5GS.GetNasKeySetIdentifiler())
-       if ue.NgKsi.Tsc == models.ScType_NATIVE && ue.NgKsi.Ksi != 7 {
+       if ue.NgKsi.Tsc == models.ScType_NATIVE && ue.NgKsi.Ksi == 0 {
+               ue.NgKsi.Tsc = models.ScType_NATIVE
+               ue.NgKsi.Ksi = 1
        } else {
                ue.NgKsi.Tsc = models.ScType_NATIVE
                ue.NgKsi.Ksi = 0
        }
+       /*if ue.NgKsi.Tsc == models.ScType_NATIVE && ue.NgKsi.Ksi != 7 {
+       } else {
+               ue.NgKsi.Tsc = models.ScType_NATIVE
+               ue.NgKsi.Ksi = 0
+       }*/

        // Copy UserLocation from ranUe
        ue.Location = ue.RanUe[anType].Location
@@ -2021,6 +2028,13 @@ func HandleAuthenticationFailure(ue *context.AmfUe, anType models.AccessType,
                                Auts: hex.EncodeToString(auts[:]),
                        }

+                       var av5gAka models.Av5gAka
+                       if err := mapstructure.Decode(ue.AuthenticationCtx.Var5gAuthData, &av5gAka); err != nil {
+                               ue.GmmLog.Error("Var5gAuthData Convert Type Error")
+                               return err
+                       }
+                       resynchronizationInfo.Rand = av5gAka.Rand
+
                        response, problemDetails, err := consumer.SendUEAuthenticationAuthenticateRequest(ue, resynchronizationInfo)
                        if err != nil {
                                return err
root@ddamf:~/anu/5gsim/pw5gc#
[Sync_Failure_WithFix_notworking.zip](https://github.com/free5gc/free5gc/files/6878076/Sync_Failure_WithFix_notworking.zip)

root@ddamf:~/anu/5gsim/pw5gc# git diff NFs/udm/producer/generate_auth_data.go
diff --git a/pw5gc/NFs/udm/producer/generate_auth_data.go b/pw5gc/NFs/udm/producer/generate_auth_data.go
index 4461eaa..d8d32a9 100644
--- a/pw5gc/NFs/udm/producer/generate_auth_data.go
+++ b/pw5gc/NFs/udm/producer/generate_auth_data.go
@@ -27,7 +27,7 @@ import (
 )

 const (
-       SqnMAx    int64 = 0x7FFFFFFFFFF
+       SqnMAx    int64 = 0xFFFFFFFFFFF
        ind       int64 = 32
        keyStrLen int   = 32
        opStrLen  int   = 32
root@ddamf:~/anu/5gsim/pw5gc#

kindly help
