### ISSUE TITLE
AMF to NRF

### ISSUE THREAD

**Issue by Lahbak** [free5gc/free5gc#56] opened 2020-06-01 15:54 UTC
After running AMF
cd $GOPATH/src/free5gc
./bin/amf

it shows me this message at THE END : 
INFO[2020-06-01T15:43:45Z]/src/amf/amf.go:25 main.main() amf                                           AMF=app
INFO[2020-06-01T15:43:45Z]/src/amf/amf.go:26 main.main() AMF version:  2020-03-31-01                   AMF=app
CommonConfig file: config/free5GC.conf
INFO[2020-06-01T15:43:45Z]/lib/nas/logger/logger.go:45 free5gc/lib/nas/logger.SetLogLevel() set log level : info                          NAS=message
INFO[2020-06-01T15:43:45Z]/lib/nas/logger/logger.go:50 free5gc/lib/nas/logger.SetReportCaller() set report call : true                        NAS=message
INFO[2020-06-01T15:43:45Z]/lib/fsm/logger/logger.go:43 free5gc/lib/fsm/logger.SetLogLevel() set log level : info                          fsm=fsm
INFO[2020-06-01T15:43:45Z]/lib/fsm/logger/logger.go:48 free5gc/lib/fsm/logger.SetReportCaller() set report call : true                        fsm=fsm
INFO[2020-06-01T15:43:45Z]/lib/ngap/logger/logger.go:43 free5gc/lib/ngap/logger.SetLogLevel() set log level : info                          NGAP=NGAP
INFO[2020-06-01T15:43:45Z]/lib/ngap/logger/logger.go:48 free5gc/lib/ngap/logger.SetReportCaller() set report call : true                        NGAP=NGAP
INFO[2020-06-01T15:43:45Z]/lib/Namf_Communication/logger/logger.go:43 
[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)
.
.
.

[GIN-debug] POST   /namf-comm/v1/ue-contexts/:ueContextId/transfer-update --> free5gc/src/amf/Communication.RegistrationStatusUpdate (4 handlers)
[GIN-debug] POST   /namf-comm/v1/ue-contexts/:ueContextId/release --> free5gc/src/amf/Communication.ReleaseUEContext (4 handlers)
[GIN-debug] POST   /namf-comm/v1/ue-contexts/:ueContextId/transfer --> free5gc/src/amf/Communication.UEContextTransfer (4 handlers)
[GIN-debug] DELETE /namf-comm/v1/ue-contexts/:ueContextId/n1-n2-messages/subscriptions/:subscriptionId --> free5gc/src/amf/Communication.N1N2MessageUnSubscribe (4 handlers)
[GIN-debug] POST   /namf-comm/v1/ue-contexts/:ueContextId/n1-n2-messages --> free5gc/src/amf/Communication.N1N2MessageTransfer (4 handlers)
[GIN-debug] GET    /namf-comm/v1/ue-contexts/:ueContextId/n1-n2-messages/:n1N2MessageId --> free5gc/src/amf/Communication.N1N2MessageTransferStatus (4 handlers)
[GIN-debug] POST   /namf-comm/v1/ue-contexts/:ueContextId/n1-n2-messages/subscriptions --> free5gc/src/amf/Communication.N1N2MessageSubscribe (4 handlers)
[GIN-debug] DELETE /namf-comm/v1/non-ue-n2-messages/subscriptions/:n2NotifySubscriptionId --> free5gc/src/amf/Communication.NonUeN2InfoUnSubscribe (4 handlers)
[GIN-debug] POST   /namf-comm/v1/non-ue-n2-messages/transfer --> free5gc/src/amf/Communication.NonUeN2MessageTransfer (4 handlers)
[GIN-debug] POST   /namf-comm/v1/non-ue-n2-messages/subscriptions --> free5gc/src/amf/Communication.NonUeN2InfoSubscribe (4 handlers)
[GIN-debug] POST   /namf-comm/v1/subscriptions --> free5gc/src/amf/Communication.AMFStatusChangeSubscribe (4 handlers)
[GIN-debug] GET    /namf-evts/v1/            --> free5gc/src/amf/EventExposure.Index (4 handlers)
[GIN-debug] DELETE /namf-evts/v1/subscriptions/:subscriptionId --> free5gc/src/amf/EventExposure.DeleteSubscription (4 handlers)
[GIN-debug] PATCH  /namf-evts/v1/subscriptions/:subscriptionId --> free5gc/src/amf/EventExposure.ModifySubscription (4 handlers)
[GIN-debug] POST   /namf-evts/v1/subscriptions --> free5gc/src/amf/EventExposure.CreateSubscription (4 handlers)
[GIN-debug] GET    /namf-mt/v1/              --> free5gc/src/amf/MT.Index (4 handlers)
[GIN-debug] GET    /namf-mt/v1/ue-contexts/:ueContextId --> free5gc/src/amf/MT.ProvideDomainSelectionInfo (4 handlers)
[GIN-debug] POST   /namf-mt/v1/ue-contexts/:ueContextId/ue-reachind --> free5gc/src/amf/MT.EnableUeReachability (4 handlers)
[GIN-debug] GET    /namf-loc/v1/             --> free5gc/src/amf/Location.Index (4 handlers)
[GIN-debug] POST   /namf-loc/v1/:ueContextId/provide-loc-info --> free5gc/src/amf/Location.ProvideLocationInfo (4 handlers)
[GIN-debug] POST   /namf-loc/v1/:ueContextId/provide-pos-info --> free5gc/src/amf/Location.ProvidePositioningInfo (4 handlers)
INFO[2020-06-01T15:43:45Z]/src/amf/amf_util/initContext.go:14 free5gc/src/amf/amf_util.InitAmfContext() amfconfig Info: Version[1.0.0] Description[AMF initial local configuration]  AMF=Util
INFO[2020-06-01T15:43:45Z]/home/release3/gofree5gc/release/src/free5gc/lib/ngap/ngapSctp/sctp.go:80 free5gc/lib/ngap/ngapSctp.Server() Listen on 127.0.0.1:38412                     NGAP=NGAP

**AMF register to NRF Error[Put https://localhost:29510/nnrf-nfm/v1/nf-instances/eca51c70-27c1-4530-bfc3-9e16e3475de5: dial tcp 127.0.0.1:29510: connect: connection refused]**

How to resolve this problem please ?

**Comment by endrigoshi** [comment] 2020-06-01 15:58
It seems that it cannot register itself to the NRF. Are you running NRF before running AMF?
Or it can be a configuration problem, where NRF is not running at `127.0.0.1` as is specified in the config file.

**Comment by Lahbak** [comment] 2020-06-01 16:14
i run the nrf 

INFO[2020-06-01T16:12:11Z]/src/nrf/nrf.go:32 main.main() NRF version:  2020-03-31-01                   NRF=app
CommonConfig file: config/free5GC.conf
INFO[2020-06-01T16:12:11Z]/lib/nas/logger/logger.go:45 free5gc/lib/nas/logger.SetLogLevel() set log level : info                          NAS=message
INFO[2020-06-01T16:12:11Z]/lib/nas/logger/logger.go:50 free5gc/lib/nas/logger.SetReportCaller() set report call : true                        NAS=message
INFO[2020-06-01T16:12:11Z]/lib/fsm/logger/logger.go:43 free5gc/lib/fsm/logger.SetLogLevel() set log level : info                          fsm=fsm
INFO[2020-06-01T16:12:11Z]/lib/fsm/logger/logger.go:48 free5gc/lib/fsm/logger.SetReportCaller() set report call : true                        fsm=fsm
INFO[2020-06-01T16:12:11Z]/lib/ngap/logger/logger.go:43 free5gc/lib/ngap/logger.SetLogLevel() set log level : info                          NGAP=NGAP
INFO[2020-06-01T16:12:11Z]/lib/ngap/logger/logger.go:48 free5gc/lib/ngap/logger.SetReportCaller() set report call : true                        NGAP=NGAP
INFO[2020-06-01T16:12:11Z]/lib/Namf_Communication/logger/logger.go:43 free5gc/lib/Namf_Communication/logger.SetLogLevel() set log level : info                          Namf=Comm
INFO[2020-06-01T16:12:11Z]/lib/Namf_Communication/logger/logger.go:48 free5gc/lib/Namf_Communication/logger.SetReportCaller() set report call : true                        Namf=Comm
INFO[2020-06-01T16:12:11Z]/lib/Namf_EventExposure/logger/logger.go:43 free5gc/lib/Namf_EventExposure/logger.SetLogLevel() set log level : info                          Namf=Event
INFO[2020-06-01T16:12:11Z]/lib/Namf_EventExposure/logger/logger.go:48 free5gc/lib/Namf_EventExposure/logger.SetReportCaller() set report call : true                        Namf=Event
INFO[2020-06-01T16:12:11Z]/lib/Nsmf_PDUSession/logger/logger.go:43 free5gc/lib/Nsmf_PDUSession/logger.SetLogLevel() set log level : info                          Nsmf=PDUSession
INFO[2020-06-01T16:12:11Z]/lib/Nsmf_PDUSession/logger/logger.go:48 free5gc/lib/Nsmf_PDUSession/logger.SetReportCaller() set report call : true                        Nsmf=PDUSession
INFO[2020-06-01T16:12:11Z]/lib/Nudr_DataRepository/logger/logger.go:43 free5gc/lib/Nudr_DataRepository/logger.SetLogLevel() set log level : info                          Nudr=DataRepository
INFO[2020-06-01T16:12:11Z]/lib/Nudr_DataRepository/logger/logger.go:48 free5gc/lib/Nudr_DataRepository/logger.SetReportCaller() set report call : true                        Nudr=DataRepository
INFO[2020-06-01T16:12:11Z]/lib/openapi/logger/logger.go:43 free5gc/lib/openapi/logger.SetLogLevel() set log level : info                          OpenApi=OpenApi
INFO[2020-06-01T16:12:11Z]/lib/openapi/logger/logger.go:48 free5gc/lib/openapi/logger.SetReportCaller() set report call : true                        OpenApi=OpenApi
INFO[2020-06-01T16:12:11Z] set log level : info                          aper=aper
INFO[2020-06-01T16:12:11Z] set report call : true                        aper=aper
INFO[2020-06-01T16:12:11Z]/lib/CommonConsumerTestData/logger/logger.go:46 free5gc/lib/CommonConsumerTestData/logger.SetLogLevel() set log level : info                          CommonTest=comm
INFO[2020-06-01T16:12:11Z]/lib/CommonConsumerTestData/logger/logger.go:51 free5gc/lib/CommonConsumerTestData/logger.SetReportCaller() set report call : true                        CommonTest=comm
INFO[2020-06-01T16:12:11Z]/src/nrf/factory/factory.go:35 free5gc/src/nrf/factory.InitConfigFactory() Successfully initialize configuration config/nrfcfg.conf  NRF=init
INFO[2020-06-01T16:12:11Z]/src/nrf/nrf_service/nrf_init.go:73 free5gc/src/nrf/nrf_service.(*NRF).Initialize() NRF debug level(string): info                 NRF=init
INFO[2020-06-01T16:12:11Z]/src/nrf/nrf_service/nrf_init.go:98 free5gc/src/nrf/nrf_service.(*NRF).Start() Server started                                NRF=init
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> free5gc/src/nrf/AccessToken.Index (3 handlers)
[GIN-debug] POST   /oauth2/token             --> free5gc/src/nrf/AccessToken.AccessTokenRequest (3 handlers)
[GIN-debug] GET    /nnrf-disc/v1/            --> free5gc/src/nrf/Discovery.Index (3 handlers)
[GIN-debug] GET    /nnrf-disc/v1/nf-instances --> free5gc/src/nrf/Discovery.SearchNFInstances (3 handlers)
[GIN-debug] GET    /nnrf-nfm/v1/             --> free5gc/src/nrf/Management.Index (3 handlers)
[GIN-debug] DELETE /nnrf-nfm/v1/nf-instances/:nfInstanceID --> free5gc/src/nrf/Management.DeregisterNFInstance (3 handlers)
[GIN-debug] GET    /nnrf-nfm/v1/nf-instances/:nfInstanceID --> free5gc/src/nrf/Management.GetNFInstance (3 handlers)
[GIN-debug] PUT    /nnrf-nfm/v1/nf-instances/:nfInstanceID --> free5gc/src/nrf/Management.RegisterNFInstance (3 handlers)
[GIN-debug] PATCH  /nnrf-nfm/v1/nf-instances/:nfInstanceID --> free5gc/src/nrf/Management.UpdateNFInstance (3 handlers)
[GIN-debug] GET    /nnrf-nfm/v1/nf-instances --> free5gc/src/nrf/Management.GetNFInstances (3 handlers)
[GIN-debug] DELETE /nnrf-nfm/v1/subscriptions/:subscriptionID --> free5gc/src/nrf/Management.RemoveSubscription (3 handlers)
[GIN-debug] PATCH  /nnrf-nfm/v1/subscriptions/:subscriptionID --> free5gc/src/nrf/Management.UpdateSubscription (3 handlers)
[GIN-debug] POST   /nnrf-nfm/v1/subscriptions --> free5gc/src/nrf/Management.CreateSubscription (3 handlers)
INFO[2020-06-01T16:12:11Z]/src/nrf/nrf_context/nrf_context.go:19 free5gc/src/nrf/nrf_context.InitNrfContext() nrfconfig Info: Version[1.0.0] Description[NRF initial local configuration]  NRF=init
INFO[2020-06-01T16:12:11Z]/src/nrf/nrf_service/nrf_init.go:111 free5gc/src/nrf/nrf_service.(*NRF).Start() 127.0.0.1:29510                               NRF=init

**Comment by Lahbak** [comment] 2020-06-01 16:15
But when i run the other function I find the same problem : 
**register to NRF Error[Put https://localhost:29510/nnrf-nfm/v1/nf-instances/eca51c70-27c1-4530-bfc3-9e16e3475de5: dial tcp 127.0.0.1:29510: connect: connection refused]**

**Comment by endrigoshi** [comment] 2020-06-01 16:19
Are you running the AMF and NRF in the same machine, or in different ones?

**Comment by Lahbak** [comment] 2020-06-01 16:20
on the same machine

**Comment by free5gc-org** [comment] 2020-06-01 20:57
Dear @Lahbak ,

For questions and support please use the [official forum](https://forum.free5gc.org). The issue list of this repo is exclusively for bug reports and feature requests.

Also,  please provide the pcap file, config zip file, kernel version, whether you have installing gtp5g module, using docker, or other useful information for debugging so that we can check what the problem is caused by.

Thanks a lot.

**Comment by free5gc-org** [comment] 2020-06-02 08:09
We may move to [forum](https://forum.free5gc.org) and close this issue.

**Closed by free5gc-org** 2020-06-02 08:09 UTC
