### ISSUE TITLE
Registration Status Update Error when connecting to a physical UE

### ISSUE THREAD

**Issue by osamirabo** [free5gc/free5gc#582] opened 2024-04-23 15:38 UTC
Hello All,

Currently we are trying to deploy a physical setup:

1. Samsung S21 Ultra as UE
2. SRSRAN as gNB
3. free5gc as a core network

When we try to connect the UE we faced the following error 

![Screenshot from 2024-04-23 17-33-17](https://github.com/free5gc/free5gc-compose/assets/28990543/81476a01-e63c-4972-98ec-172bbd890ba7)

[WARN][AMF][Gmm] RequestedNssai[{Sst:1 Sd:}] is not supported by AMF
[ERRO][AMF][Gmm][amf_ue_ngap_id:RU:0,AU:1(3GPP)][supi:SUPI:imsi-001010000000001] Registration Status Update Error[: server no response]

It seems that the UE is sending Sst:1 and empty Sd but the core doesn't support Sd to be empty. Is there a workaround for this scenario ?

**Comment by ianchen0119** [comment] 2024-07-08 10:18
Hi @andy89923 

Please help to assign the assignee.

Thanks.

**Comment by juanjuan2** [comment] 2024-07-13 13:26
I meet the same problem. Do you solve it?

**Comment by andy89923** [comment] 2024-07-13 13:29
The problem is that free5GC does not support empty SD value!
We are fixing this issue, and it will be released soon.

**Closed** 2024-08-22 10:46 UTC

**Comment by andy89923** [comment] 2024-08-22 15:20
Hi, the PR had been merged. You can checkout to latest commit and test it.

If you encounter any problems, just post it here and reopen the issue. Thanks!
